Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 968
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 985
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 959
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /static/chipin/logo_90.jpg HTTP/1.1" 200 2283
"GET /chipin/ HTTP/1.1" 200 977
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/create_group/ HTTP/1.1" 200 1272
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/create_group/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1143
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /admin/ HTTP/1.1" 200 6671
"GET /admin/auth/user/ HTTP/1.1" 200 12670
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 22418
"GET /static/admin/css/forms.css HTTP/1.1" 304 0
"GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/auth/user/1/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 12870
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/ HTTP/1.1" 200 10983
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 12673
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 22441
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/group/ HTTP/1.1" 200 8130
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 12673
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /chipin/group/1/ HTTP/1.1" 200 991
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 964
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1139
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 991
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/invite/ HTTP/1.1" 200 1423
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/invite/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1125
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 972
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1297
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/accept-invite/1/?user_id=2 HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1205
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /users/login/ HTTP/1.1" 200 1053
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
- Broken pipe from ('127.0.0.1', 51385)
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 964
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 22393
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/ HTTP/1.1" 200 10983
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/2/change/ HTTP/1.1" 200 11793
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/ HTTP/1.1" 200 10983
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 12673
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/group/ HTTP/1.1" 200 8130
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 12673
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/ HTTP/1.1" 200 10983
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/2/change/ HTTP/1.1" 200 11793
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/2/delete/ HTTP/1.1" 200 7734
"GET /static/admin/js/cancel.js HTTP/1.1" 200 884
"POST /admin/users/profile/2/delete/ HTTP/1.1" 302 0
"GET /admin/users/profile/ HTTP/1.1" 200 10727
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/users/profile/add/ HTTP/1.1" 200 11593
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/users/profile/add/ HTTP/1.1" 302 0
"GET /admin/users/profile/ HTTP/1.1" 200 11208
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1142
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 1036
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\chipin\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 200 1176
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /users/register/ HTTP/1.1" 200 2762
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/register/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1208
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 971
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1489
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 1305
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/request-to-join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1460
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 1305
"GET /chipin/group/1/request-to-join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1453
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 1597
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/request/1/vote/approve/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1597
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/request/1/vote/approve/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1722
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 972
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1599
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 1539
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/request/1/vote/approve/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 1557
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Watching for file changes with StatReloader
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2179
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2586
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/ HTTP/1.1" 200 2709
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/edit/1/ HTTP/1.1" 200 2604
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/edit/1/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2582
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/comment/1/delete/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2179
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2581
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/comment/2/delete/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2179
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2600
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 971
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1800
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2352
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Watching for file changes with StatReloader
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/logo_90.jpg HTTP/1.1" 304 0
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2600
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/comment/3/delete/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2179
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2179
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\ssa_project\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\ssa_project\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /chipin/group/1/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/group/1/ HTTP/1.1" 404 2546
"GET /chipin/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/ HTTP/1.1" 404 2538
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2414
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/create_event/ HTTP/1.1" 200 1472
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/create_event/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3694
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3645
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 971
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1800
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 3169
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3296
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/leave/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3354
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3296
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 967
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 3458
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/delete/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 2589
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2512
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"GET /static/chipin/logo_90.jpg HTTP/1.1" 304 0
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'user' is not a registered namespace
"GET /users/ HTTP/1.1" 500 152113
"GET /users/ HTTP/1.1" 200 981
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /users/ HTTP/1.1" 200 981
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'user' is not a registered namespace
"GET /users/ HTTP/1.1" 500 152113
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150762
Forbidden (CSRF token from POST incorrect.): /users/login/
"POST /users/login/ HTTP/1.1" 403 2503
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150449
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150723
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150449
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150723
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 69, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150449
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 93, in user
    return render(request, "users/user.html")
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'top_up' not found. 'top_up' is not a valid view function or pattern name.
"GET /users/ HTTP/1.1" 500 150510
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
C:\Users\daddy\ssa_project\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2512
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"GET /static/chipin/logo_90.jpg HTTP/1.1" 304 0
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 30, in top_up
    form = TopUpForm(user=request.user)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\forms.py", line 238, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: BaseModelForm.__init__() got an unexpected keyword argument 'user'
"GET /users/top-up/ HTTP/1.1" 500 68182
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view users.views.top_up didn't return an HttpResponse object. It returned None instead.
"GET /users/top-up/ HTTP/1.1" 500 64432
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view users.views.top_up didn't return an HttpResponse object. It returned None instead.
"GET /users/top-up/ HTTP/1.1" 500 64295
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view users.views.top_up didn't return an HttpResponse object. It returned None instead.
"GET /users/top-up/ HTTP/1.1" 500 64295
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2512
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"GET /static/chipin/logo_90.jpg HTTP/1.1" 304 0
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 34, in top_up
    'welcome_message': f"Welcome back, {request.user.nickname}!",
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
AttributeError: 'User' object has no attribute 'nickname'
"GET /users/top-up/ HTTP/1.1" 500 67944
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 35, in top_up
    'welcome_message': f"Welcome back, {request.user.nickname}!",
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
AttributeError: 'User' object has no attribute 'nickname'
"GET /users/top-up/ HTTP/1.1" 500 68068
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 35, in top_up
    'welcome_message': f"Welcome back, {request.user.nickname}!",
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
AttributeError: 'User' object has no attribute 'nickname'
- Broken pipe from ('127.0.0.1', 52841)
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 35, in top_up
    'welcome_message': f"Welcome back, {request.user.nickname}!",
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
AttributeError: 'User' object has no attribute 'nickname'
"GET /users/top-up/ HTTP/1.1" 500 67931
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 35, in top_up
    'welcome_message': f"Welcome back, {request.user.nickname}!",
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
AttributeError: 'User' object has no attribute 'nickname'
"GET /users/top-up/ HTTP/1.1" 500 67931
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/top-up/ HTTP/1.1" 200 2528
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /users/top-up/ HTTP/1.1" 200 2528
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\users\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 32, in top_up
    form = TopUpForm()
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\models.py", line 362, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /users/top-up/ HTTP/1.1" 500 69670
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 33, in top_up
    form = TopUpForm(forms.ModelForm)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\models.py", line 362, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /users/top-up/ HTTP/1.1" 500 69781
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2461
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 32, in top_up
    form = TopUpForm()
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\models.py", line 362, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /users/top-up/ HTTP/1.1" 500 69670
"GET /chipin/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/ HTTP/1.1" 404 2538
"GET /chipin/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/ HTTP/1.1" 404 2538
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1081
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1599
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /users/top-up/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\ssa_project\users\views.py", line 32, in top_up
    form = TopUpForm()
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\forms\models.py", line 362, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /users/top-up/ HTTP/1.1" 500 69670
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 2414
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/create_event/ HTTP/1.1" 200 1472
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /chipin/group/1/create_event/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3684
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3635
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/leave/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3693
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/event/1/join/ HTTP/1.1" 302 0
"GET /chipin/group/1/ HTTP/1.1" 200 3635
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /chipin/group/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 339, in group_detail
    return render(request, 'chipin/group_detail.html', {
        'group': group,
    ...<5 lines>...
        'is_member': is_member,
    })
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 101: 'endfor', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
"GET /chipin/group/1/ HTTP/1.1" 500 244912
"GET /chipin/group/1/ HTTP/1.1" 200 3480
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /chipin/group/1/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/group/1/ HTTP/1.1" 404 2546
"GET /chipin/group/1/create_event/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/group/1/create_event/ HTTP/1.1" 404 2559
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/group/1/ HTTP/1.1" 404 2546
Not Found: /accounts/login/
"GET /accounts/login/?next=/chipin/group/1/ HTTP/1.1" 404 2546
"GET /users/ HTTP/1.1" 302 0
"GET /users/login/?next=/users/ HTTP/1.1" 200 1053
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /chipin/group/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 339, in group_detail
    return render(request, 'chipin/group_detail.html', {
        'group': group,
    ...<5 lines>...
        'is_member': is_member,
    })
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'transfer_funds' not found. 'transfer_funds' is not a valid view function or pattern name.
"GET /chipin/group/1/ HTTP/1.1" 500 205998
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /chipin/group/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 339, in group_detail
    return render(request, 'chipin/group_detail.html', {
        'group': group,
    ...<5 lines>...
        'is_member': is_member,
    })
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'transfer_funds' not found. 'transfer_funds' is not a valid view function or pattern name.
"GET /chipin/group/1/ HTTP/1.1" 500 205950
Internal Server Error: /chipin/group/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 339, in group_detail
    return render(request, 'chipin/group_detail.html', {
        'group': group,
    ...<5 lines>...
        'is_member': is_member,
    })
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'transfer_funds' not found. 'transfer_funds' is not a valid view function or pattern name.
"GET /chipin/group/1/ HTTP/1.1" 500 205950
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /chipin/group/1/ HTTP/1.1" 200 3556
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1182
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"POST /users/login/ HTTP/1.1" 302 0
"GET /users/ HTTP/1.1" 200 1076
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/ HTTP/1.1" 200 1596
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
"GET /chipin/group/1/ HTTP/1.1" 200 3556
"GET /static/chipin/styles.css HTTP/1.1" 404 1865
Internal Server Error: /chipin/transfer_funds/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 33, in transfer_funds
    event = get_object_or_404(id=event_id)
TypeError: get_object_or_404() missing 1 required positional argument: 'klass'
"GET /chipin/transfer_funds/1/ HTTP/1.1" 500 72777
Internal Server Error: /chipin/transfer_funds/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 33, in transfer_funds
    event = get_object_or_404(id=event_id)
TypeError: get_object_or_404() missing 1 required positional argument: 'klass'
"GET /chipin/transfer_funds/1/ HTTP/1.1" 500 72777
Internal Server Error: /chipin/transfer_funds/1/
Traceback (most recent call last):
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\daddy\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "C:\Users\daddy\ssa_project\chipin\views.py", line 33, in transfer_funds
    event = get_object_or_404(id=event_id)
TypeError: get_object_or_404() missing 1 required positional argument: 'klass'
"GET /chipin/transfer_funds/1/ HTTP/1.1" 500 72777
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\daddy\ssa_project\chipin\views.py changed, reloading.
Watching for file changes with StatReloader
